#!/bin/bash
export MSYS_NO_PATHCONV=1
set -e

S2I_EXE=s2i
if [ -z "$(type -P "$S2I_EXE")" ]; then
  echo -e "The ${S2I_EXE} executable is needed and not on your path."
  echo -e "It can be downloaded from here: https://github.com/openshift/source-to-image"
  echo -e "Make sure you place it in a directory on your path."
  exit 1
fi

SCRIPT_HOME="$(cd "$(dirname "$0")" && pwd)"
export COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME-jag-probate}"

# =================================================================================================================
# Usage:
# -----------------------------------------------------------------------------------------------------------------
usage() {
  cat <<-EOF

  Usage: $0 {start|debug|stop|build|rm|down}

  Options:

  build - Build the docker images for the project.
          You need to do this first, since the builds require some s2i builds.
          You can build individual components as shown below, components that have dependencies
          will have these dependencies built too.  By default all components are built.

          Examples:
          - Build everything:
            $0 build
          - Build the api only:
            $0 build api
          - Build the web only:
            $0 build web-dev

          Containers:
            - api
            - web-dev

  start - Creates the application containers from the built images
          and starts the services based on the docker-compose.yaml file.
          Example:
            $0 start

  debug - Used for local development that enables hot reloading for BE.
          Creates the application containers from the built images
          and starts the services based on the docker-compose.yaml file.
          Example:
            $0 debug

  stop - Stops the services.  This is a non-destructive process.  The containers
         are not deleted so they will be reused the next time you run start.

  down | rm - Brings down the services and removes the volumes (storage) and containers. Destructive.
EOF
exit 1
}
# -----------------------------------------------------------------------------------------------------------------
# Default Settings:
# -----------------------------------------------------------------------------------------------------------------
RUNTIME_CONTAINERS="db api web"
DEBUG_CONTAINERS="db api web"
# -----------------------------------------------------------------------------------------------------------------
# Functions:
# -----------------------------------------------------------------------------------------------------------------
build-all() {
  build-web
  build-api
}

build-api() {
  #
  # api
  #
  echo -e "\n\n===================================================================================================="
  echo -e "Building api image using docker ..."
  echo -e "----------------------------------------------------------------------------------------------------"
  docker build \
    -t "${COMPOSE_PROJECT_NAME}-api" \
    -f './api/Dockerfile.dev' '..'

  echo -e "===================================================================================================="
}

build-web() {
  #
  # web
  #
  echo -e "\n\n===================================================================================================="
  echo -e "Building the ${COMPOSE_PROJECT_NAME}-web image using Docker ..."
  echo -e "----------------------------------------------------------------------------------------------------"
  docker build \
    -t "${COMPOSE_PROJECT_NAME}-web" \
    --build-arg NODE_VERSION=22 \
    --build-arg VITE_PORT=8080 \
    --build-arg WEB_SRC='./web' \
    -f './web/Dockerfile.local' '..'
  echo -e "===================================================================================================="
}

configureEnvironment () {

  if [ -f .env ]; then
    echo -e "\nLoading environment variables from .env ...\n"
    source .env
  fi

  for arg in $@; do
    case "$arg" in
      *=*)
        export ${arg}
        ;;
    esac
  done

  # Default database startup parameters
  export POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE:-probatedb}
  export POSTGRESQL_USER=${POSTGRESQL_USER:-probate}
  export POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD:-probate123}
  export POSTGRESQL_ADMIN_PASSWORD=${POSTGRESQL_ADMIN_PASSWORD:-admin123}

  # Default API startup parameters
  export API_URL=${API_URL-http://api:5000/api/}
}

getStartupParams() {
  CONTAINERS=""
  ARGS=""

  for arg in $@; do
    case "$arg" in
      *=*)
        # Skip it
        ;;
     -*)
        ARGS+=" $arg";;
      *)
        CONTAINERS+=" $arg";;
    esac
  done

  if [ -z "$CONTAINERS" ]; then
      if [ -z "$DEBUG_MODE" ]; then
        CONTAINERS="$RUNTIME_CONTAINERS"
      else
        CONTAINERS="$DEBUG_CONTAINERS"
      fi
  fi

  echo ${ARGS} ${CONTAINERS}
}

toLower() {
  echo $(echo ${@} | tr '[:upper:]' '[:lower:]')
}

functionExists() {
  (
    if [ ! -z ${1} ] && type ${1} &>/dev/null; then
      return 0
    else
      return 1
    fi
  )
}

deleteVolumes() {
  _projectName=${COMPOSE_PROJECT_NAME:-docker}

  echo "Stopping and removing any running containers ..."
  docker-compose down -v

  _pattern="^${_projectName}_\|^docker_"
  _volumes=$(docker volume ls -q | grep ${_pattern} | cat)

  if [ ! -z "${_volumes}" ]; then
    echo "Removing project volumes ..."
    echo ${_volumes} | xargs docker volume rm
  else
    echo "No project volumes exist."
  fi

  echo "Removing build cache ..."
  rm -Rf ../api/bin
  rm -Rf ../api/obj
  rm -Rf ../db/bin
  rm -Rf ../db/obj
}
# =================================================================================================================

pushd ${SCRIPT_HOME} >/dev/null
COMMAND=$(toLower ${1})
shift

case "$COMMAND" in
  start)
    _startupParams=$(getStartupParams $@)
    configureEnvironment $@
    docker-compose up ${_startupParams}
    ;;
  debug)
    export DEBUG_MODE=1
    _startupParams=$(getStartupParams $@)
    configureEnvironment $@
    docker-compose up ${_startupParams}
    ;;
  stop)
    docker-compose stop
    ;;
  rm|down)
    configureEnvironment
    deleteVolumes
    ;;
  build)
    buildImage=$(toLower ${1})
    shift || buildImage=all
    buildImage=$(echo ${buildImage} | sed s~^vcr-~~)
    case "$buildImage" in
      *=*)
        buildImage=all
        ;;
    esac

    if functionExists "build-${buildImage}"; then
      eval "build-${buildImage}"
    else
      echo -e "Error:\nThe build function, build-${buildImage}, does not exist.  Please check your build parameters and try again.\nUse '-h' to get full help details."
      exit 1
    fi
    ;;
  *)
    usage
esac

popd >/dev/null
